### PR TITLE
Version 3.5.1

### LINKED ISSUE #50: No PNG support in R 3.4.1-hff14c37_5
Issue: I just created a new environment  with
```conda create -n bioc r-base=3.4.1 rstudio r-tidyverse bioconductor-deseq2 bioconductor-edger bioconductor-biostrings bioconductor-bsgenome```
And there isn't PNG support
```
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE       FALSE       FALSE        TRUE        TRUE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE        TRUE       FALSE        TRUE        TRUE        TRUE 
```

I tested an environment with `R=3.4.3-4` and `png` was supported, but  `rstudio` needs `r-base 3.4.1-hff14c37_5` which apparently has this problem.

`r-base:                    3.4.1-4                 conda-forge --> 3.4.1-hff14c37_5       conda-forge`

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /media/mibu/Storage_SSD/Miniconda3/envs/bioconductor:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.0                     mro_2  
backcall                  0.1.0                      py_0    conda-forge
binutils_impl_linux-64    2.28.1               had2808c_3  
binutils_linux-64         7.2.0               had2808c_27  
bioconductor-annotate     1.56.0                 r3.4.1_0    bioconda
bioconductor-annotationdbi 1.40.0                 r3.4.1_0    bioconda
bioconductor-biobase      2.38.0                 r3.4.1_0    bioconda
bioconductor-biocgenerics 0.24.0                 r3.4.1_0    bioconda
bioconductor-biocparallel 1.12.0                 r3.4.1_0    bioconda
bioconductor-biostrings   2.46.0                 r3.4.1_0    bioconda
bioconductor-bsgenome     1.46.0                 r3.4.1_0    bioconda
bioconductor-delayedarray 0.4.1                  r3.4.1_0    bioconda
bioconductor-deseq2       1.18.1                 r3.4.1_1    bioconda
bioconductor-edger        3.20.7                 r3.4.1_0    bioconda
bioconductor-genefilter   1.60.0                 r3.4.1_0    bioconda
bioconductor-geneplotter  1.56.0                 r3.4.1_0    bioconda
bioconductor-genomeinfodb 1.14.0                 r3.4.1_0    bioconda
bioconductor-genomeinfodbdata 1.0.0                  r3.4.1_1    bioconda
bioconductor-genomicalignments 1.14.1                 r3.4.1_0    bioconda
bioconductor-genomicranges 1.30.3                 r3.4.1_0    bioconda
bioconductor-iranges      2.12.0                 r3.4.1_0    bioconda
bioconductor-limma        3.34.9                 r3.4.1_0    bioconda
bioconductor-rsamtools    1.30.0                 r3.4.1_0    bioconda
bioconductor-rtracklayer  1.38.3                 r3.4.1_0    bioconda
bioconductor-s4vectors    0.16.0                 r3.4.1_0    bioconda
bioconductor-summarizedexperiment 1.8.0                  r3.4.1_0    bioconda
bioconductor-tximport     1.6.0                  r3.4.1_0    bioconda
bioconductor-xvector      0.18.0                 r3.4.1_0    bioconda
bioconductor-zlibbioc     1.24.0                 r3.4.1_0    bioconda
bleach                    1.4.2                    py36_0    bioconda
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.12              h77bcde2_0  
certifi                   2018.4.16                py36_0    conda-forge
curl                      7.60.0                        0    conda-forge
cyrus-sasl                2.1.26                        1    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
expat                     2.2.5                hfc679d8_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 h6964260_0  
font-ttf-inconsolata      2.001                hcb22688_0  
font-ttf-source-code-pro  2.030                h7457263_0  
font-ttf-ubuntu           0.83                 h8b1ccd4_0  
fontconfig                2.12.6                        0    conda-forge
fonts-anaconda            1                    h8fa9717_0  
freetype                  2.8.1                         0    conda-forge
fribidi                   1.0.4                h14c3975_0  
gcc_impl_linux-64         7.2.0                habb00fd_3  
gcc_linux-64              7.2.0               h550dcbe_27  
gfortran_impl_linux-64    7.2.0                hdf63c60_3  
gfortran_linux-64         7.2.0               h550dcbe_27  
glib                      2.53.6               h5d9569c_2  
gmp                       6.1.2                hfc679d8_0    conda-forge
graphite2                 1.3.11               hfc679d8_0    conda-forge
gsl                       2.1                           2    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
gxx_impl_linux-64         7.2.0                hdf63c60_3  
gxx_linux-64              7.2.0               h550dcbe_27  
harfbuzz                  1.7.6                hc5b324e_0  
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.4.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
jedi                      0.12.0                   py36_0    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jpeg                      9c                   h470a237_0    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter_client            5.2.3                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
krb5                      1.14.6                        0    conda-forge
libedit                   3.1.20170329         haf1bffa_0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran-ng            7.2.0                hdf63c60_3  
libiconv                  1.15                 h470a237_1    conda-forge
libntlm                   1.4                  h470a237_1    conda-forge
libpng                    1.6.34               ha92aebf_1    conda-forge
libsodium                 1.0.16                        0    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                he6b73bb_1    conda-forge
libuuid                   1.0.3                         1    conda-forge
libxcb                    1.13                 h470a237_0    conda-forge
libxml2                   2.9.8                h422b904_1    conda-forge
markupsafe                1.0                      py36_0    conda-forge
mistune                   0.8.3                    py36_1    conda-forge
mro-base                  3.4.3                h1c2f66e_0  
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   6.1                           0    conda-forge
notebook                  5.5.0                    py36_0    conda-forge
openssl                   1.0.2o                        0    conda-forge
pandoc                    2.2.1                         0    conda-forge
pandocfilters             1.4.2                    py36_0    conda-forge
pango                     1.42.0               h377f3fa_0  
parso                     0.3.0                      py_0    conda-forge
pcre                      8.39                          0    conda-forge
pexpect                   4.6.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       9.0.3                    py36_0    conda-forge
pixman                    0.34.0                        2    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
ptyprocess                0.6.0                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
python                    3.6.4                hc3d631a_1  
python-dateutil           2.7.3                      py_0    conda-forge
pyzmq                     17.0.0                   py36_4    conda-forge
qt                        5.6.2                         7    conda-forge
r-abind                   1.4_5                  r3.4.1_0    conda-forge
r-acepack                 1.4.1                  r3.4.1_0    conda-forge
r-assertthat              0.2.0                  r3.4.1_0    conda-forge
r-backports               1.1.2                  r3.4.1_0    conda-forge
r-base                    3.4.1                hff14c37_5    conda-forge
r-base64enc               0.1_3                  r3.4.1_0    conda-forge
r-bh                      1.66.0_1               r3.4.1_0    conda-forge
r-bindr                   0.1.1                  r3.4.1_0    conda-forge
r-bindrcpp                0.2                    r3.4.1_0    conda-forge
r-bit                     1.1_12                 r3.4.1_0    conda-forge
r-bit64                   0.9_5                  r3.4.1_0    conda-forge
r-bitops                  1.0_6                  r3.4.1_0    conda-forge
r-blob                    1.1.1                  r3.4.1_0    conda-forge
r-boot                    1.3_20                 r3.4.1_0    conda-forge
r-broom                   0.4.4                  r3.4.1_0    conda-forge
r-caret                   6.0_79                 r3.4.1_0    conda-forge
r-catools                 1.17.1                 r3.4.1_0    conda-forge
r-cellranger              1.1.0                  r3.4.1_0    conda-forge
r-checkmate               1.8.5                  r3.4.1_0    conda-forge
r-class                   7.3_14                 r3.4.1_0    conda-forge
r-cli                     1.0.0                  r3.4.1_0    conda-forge
r-cluster                 2.0.6                  r3.4.1_0    conda-forge
r-codetools               0.2_15                 r3.4.1_0    conda-forge
r-colorspace              1.3_2                  r3.4.1_0    conda-forge
r-config                  0.2                    r3.4.1_0    conda-forge
r-crayon                  1.3.4                  r3.4.1_0    conda-forge
r-curl                    3.2                    r3.4.1_0    conda-forge
r-cvst                    0.2_1                  r3.4.1_0    conda-forge
r-data.table              1.10.4                 r3.4.1_0    bioconda
r-dbi                     1.0.0                    r341_0    conda-forge
r-dbplyr                  1.2.1                    r341_1    conda-forge
r-ddalpha                 1.3.4                    r341_0    conda-forge
r-deoptimr                1.0_8                  r3.4.1_0    bioconda
r-dichromat               2.0_0                  r3.4.1_0    conda-forge
r-digest                  0.6.15                 r3.4.1_0    conda-forge
r-dimred                  0.1.0                  r3.4.1_0    conda-forge
r-dplyr                   0.7.4                  r3.4.1_0    conda-forge
r-drr                     0.0.3                  r3.4.1_0    conda-forge
r-essentials              3.4.1                  r3.4.1_0    conda-forge
r-evaluate                0.10.1                 r3.4.1_0    conda-forge
r-forcats                 0.3.0                  r3.4.1_0    conda-forge
r-foreach                 1.4.4                  r3.4.1_0    conda-forge
r-foreign                 0.8_67                 r3.4.1_0    conda-forge
r-formatr                 1.5                    r3.4.1_0    conda-forge
r-formula                 1.2_1                  r3.4.1_0    conda-forge
r-futile.logger           1.4.3                  r3.4.1_0    conda-forge
r-futile.options          1.0.0                  r3.4.1_0    conda-forge
r-gdata                   2.18.0                 r3.4.1_0    conda-forge
r-geometry                0.3_6                  r3.4.1_0    conda-forge
r-getopt                  1.20.2                 r3.4.1_0    conda-forge
r-ggplot2                 2.2.1                  r3.4.1_0    conda-forge
r-gistr                   0.4.2                    r341_0    conda-forge
r-glmnet                  2.0_5                  r3.4.1_0    conda-forge
r-glue                    1.2.0                  r3.4.1_0    conda-forge
r-gower                   0.1.2                  r3.4.1_0    conda-forge
r-gplots                  3.0.1                  r3.4.1_0    conda-forge
r-gridextra               2.3                    r3.4.1_0    conda-forge
r-gtable                  0.2.0                  r3.4.1_0    conda-forge
r-gtools                  3.8.1                    r341_0    conda-forge
r-haven                   1.1.2                    r341_0    conda-forge
r-hexbin                  1.27.2                 r3.4.1_0    conda-forge
r-highr                   0.7                      r341_0    conda-forge
r-hmisc                   4.0_3                  r3.4.1_0    conda-forge
r-hms                     0.3                    r3.4.1_0    conda-forge
r-htmltable               1.9                    r3.4.1_0    conda-forge
r-htmltools               0.3.6                  r3.4.1_0    conda-forge
r-htmlwidgets             1.0                    r3.4.1_0    conda-forge
r-httpuv                  1.3.6.2                r3.4.1_0    conda-forge
r-httr                    1.3.1                  r3.4.1_0    conda-forge
r-ipred                   0.9_6                  r3.4.1_0    conda-forge
r-irdisplay               0.4.4                  r3.4.1_0    conda-forge
r-irkernel                0.8.11                 r3.4.1_0    conda-forge
r-iterators               1.0.9                  r3.4.1_0    conda-forge
r-jsonlite                1.5                    r3.4.1_0    conda-forge
r-kernlab                 0.9_25                 r3.4.1_0    conda-forge
r-kernsmooth              2.23_15                r3.4.1_0    conda-forge
r-knitr                   1.20                   r3.4.1_0    conda-forge
r-labeling                0.3                    r3.4.1_0    conda-forge
r-lambda.r                1.2                    r3.4.1_0    conda-forge
r-lattice                 0.20_34                r3.4.1_0    conda-forge
r-latticeextra            0.6_28                 r3.4.1_0    conda-forge
r-lava                    1.6.1                  r3.4.1_0    conda-forge
r-lazyeval                0.2.1                  r3.4.1_0    conda-forge
r-locfit                  1.5_9.1                r3.4.1_0    conda-forge
r-lubridate               1.7.4                  r3.4.1_0    conda-forge
r-magic                   1.5_6                  r3.4.1_0    conda-forge
r-magrittr                1.5                    r3.4.1_0    conda-forge
r-maps                    3.3.0                  r3.4.1_0    conda-forge
r-markdown                0.8                    r3.4.1_1    conda-forge
r-mass                    7.3_48                 r3.4.1_0    conda-forge
r-matrix                  1.2_14                 r3.4.1_0    conda-forge
r-matrixstats             0.53.1                   r341_0    conda-forge
r-memoise                 1.1.0                  r3.4.1_0    conda-forge
r-mgcv                    1.8_24                   r341_0    conda-forge
r-mime                    0.5                    r3.4.1_0    conda-forge
r-miniui                  0.1.1                  r3.4.1_0    conda-forge
r-mnormt                  1.5_5                  r3.4.1_0    conda-forge
r-modelmetrics            1.1.0                  r3.4.1_0    conda-forge
r-modelr                  0.1.2                    r341_0    conda-forge
r-mongolite               1.4             mro343h086d26f_0  
r-munsell                 0.5.0                    r341_0    conda-forge
r-nlme                    3.1_131                r3.4.1_0    conda-forge
r-nnet                    7.3_12                 r3.4.1_0    conda-forge
r-numderiv                2016.8_1               r3.4.1_0    conda-forge
r-odbc                    1.1.3           mro343h599a50d_0  
r-openssl                 1.0.1                  r3.4.1_0    conda-forge
r-packrat                 0.4.9                  r3.4.1_0    conda-forge
r-pbdzmq                  0.3_2                  r3.4.1_0    conda-forge
r-pillar                  1.2.2            r341h6115d3f_1    conda-forge
r-pkgconfig               2.0.1                  r3.4.1_0    conda-forge
r-pki                     0.1_3                  r3.4.1_0    conda-forge
r-plogr                   0.1_1                  r3.4.1_0    conda-forge
r-pls                     2.6_0                  r3.4.1_0    conda-forge
r-plyr                    1.8.4                  r3.4.1_0    conda-forge
r-prettyunits             1.0.2                  r3.4.1_0    conda-forge
r-prodlim                 2018.04.18             r3.4.1_0    conda-forge
r-profvis                 0.3.4           mro343h086d26f_0  
r-pryr                    0.1.4                  r3.4.1_0    conda-forge
r-psych                   1.5.8                  r3.4.1_0    bioconda
r-purrr                   0.2.4                  r3.4.1_0    conda-forge
r-quantmod                0.4_8                  r3.4.1_0    conda-forge
r-r6                      2.2.2                  r3.4.1_0    conda-forge
r-randomforest            4.6_12                 r3.4.1_0    conda-forge
r-rappdirs                0.3.1                  r3.4.1_0    conda-forge
r-rbokeh                  0.5.0                  r3.4.1_0    conda-forge
r-rcolorbrewer            1.1_2                  r3.4.1_0    conda-forge
r-rcpp                    0.12.15                r3.4.1_0    conda-forge
r-rcpparmadillo           0.8.500.0              r3.4.1_0    conda-forge
r-rcpproll                0.2.2                  r3.4.1_0    conda-forge
r-rcurl                   1.95_4.8               r3.4.1_0    conda-forge
r-readr                   1.1.1                  r3.4.1_0    conda-forge
r-readxl                  1.1.0                    r341_0    conda-forge
r-recipes                 0.1.3                    r341_0    conda-forge
r-recommended             3.4.1                  r3.4.1_0    conda-forge
r-rematch                 1.0.1                  r3.4.1_0    conda-forge
r-repr                    0.15                     r341_0    conda-forge
r-reshape2                1.4.3                  r3.4.1_0    conda-forge
r-rjava                   0.9_9           mro343h086d26f_0  
r-rjdbc                   0.2_5           mro343h889e2dd_0  
r-rjson                   0.2.15                 r3.4.1_0    conda-forge
r-rjsonio                 1.3_0                  r3.4.1_0    conda-forge
r-rlang                   0.2.1                    r341_0    conda-forge
r-rmarkdown               1.9                      r341_0    conda-forge
r-robustbase              0.92_7                 r3.4.1_0    conda-forge
r-rpart                   4.1_13                 r3.4.1_0    conda-forge
r-rprojroot               1.3_2                  r3.4.1_0    conda-forge
r-rsconnect               0.8.5           mro343h889e2dd_0  
r-rsqlite                 2.0                    r3.4.1_0    conda-forge
r-rstudioapi              0.7                    r3.4.1_0    conda-forge
r-rvest                   0.3.2                  r3.4.1_0    conda-forge
r-scales                  0.5.0                  r3.4.1_0    conda-forge
r-selectr                 0.3_1                  r3.4.1_0    conda-forge
r-sfsmisc                 1.1_1                  r3.4.1_0    conda-forge
r-shiny                   1.0.5                  r3.4.1_0    conda-forge
r-snow                    0.4_2                  r3.4.1_0    conda-forge
r-sourcetools             0.1.6                  r3.4.1_0    conda-forge
r-sparklyr                0.8.2                  r3.4.1_0    conda-forge
r-spatial                 7.3_11                 r3.4.1_0    conda-forge
r-squarem                 2017.10_1              r3.4.1_0    conda-forge
r-stringi                 1.1.7                  r3.4.1_1    conda-forge
r-stringr                 1.3.0                  r3.4.1_0    conda-forge
r-survival                2.40_1                 r3.4.1_0    conda-forge
r-tibble                  1.4.2                  r3.4.1_0    conda-forge
r-tidyr                   0.8.1                    r341_0    conda-forge
r-tidyselect              0.2.4                  r3.4.1_0    conda-forge
r-tidyverse               1.1.1                  r3.4.1_0    conda-forge
r-timedate                3012.100               r3.4.1_0    conda-forge
r-ttr                     0.23_1                 r3.4.1_0    conda-forge
r-utf8                    1.1.3                  r3.4.1_0    conda-forge
r-uuid                    0.1_2                  r3.4.1_0    conda-forge
r-viridis                 0.5.1                  r3.4.1_0    conda-forge
r-viridislite             0.3.0                  r3.4.1_0    conda-forge
r-withr                   2.1.1                  r3.4.1_0    conda-forge
r-xml                     3.98_1.6               r3.4.1_0    conda-forge
r-xml2                    1.2.0                    r341_0    conda-forge
r-xtable                  1.8_2                  r3.4.1_0    conda-forge
r-xts                     0.10_1                 r3.4.1_0    conda-forge
r-yaml                    2.1.18                 r3.4.1_0    conda-forge
r-zoo                     1.8_1                  r3.4.1_0    conda-forge
readline                  7.0                  ha6073c6_4  
rstudio                   1.1.383              h2c9cdda_2  
send2trash                1.5.0                      py_0    conda-forge
setuptools                39.2.0                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.20.1                        0    conda-forge
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tk                        8.6.7                         0    conda-forge
tornado                   5.0.2                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
unixodbc                  2.3.5                h09ba92c_1    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
wget                      1.19.5               h1ad7b7a_0  
wheel                     0.31.0                   py36_0    conda-forge
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                         2    conda-forge
xorg-libsm                1.2.2                         2    conda-forge
xorg-libx11               1.6.5                         0    conda-forge
xorg-libxau               1.0.8                h470a237_4    conda-forge
xorg-libxdmcp             1.1.2                h470a237_4    conda-forge
xorg-libxext              1.3.3                         2    conda-forge
xorg-libxrender           0.9.10                        0    conda-forge
xorg-renderproto          0.11.1               h470a237_2    conda-forge
xorg-xextproto            7.3.0                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xz                        5.2.3                         0    conda-forge
zeromq                    4.2.5                hfc679d8_3    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
active environment : bioc
    active env location : /media/mibu/Storage_SSD/Miniconda3/envs/bioc
            shell level : 1
       user config file : /home/mibu/.condarc
 populated config files : /home/mibu/.condarc
          conda version : 4.5.5
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : /media/mibu/Storage_SSD/Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /media/mibu/Storage_SSD/Miniconda3/pkgs
                          /home/mibu/.conda/pkgs
       envs directories : /media/mibu/Storage_SSD/Miniconda3/envs
                          /home/mibu/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.5 requests/2.18.4 CPython/3.6.5 Linux/4.14.52-1-MANJARO manjaro/17.1.11 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


```
</details>

### PR DESCRIPTION
**Pull request by dpryan79**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This PR bumps the R version to 3.5.1. I had to modify patch 0011 to get this to compile properly, so someone who know whether that patch is even still relevant should have a look. The other patches have been modified to actually apply to R 3.5.1. This additionally fixes #50 going forward, though I notice that @bgruening just added a similar test to `master`.

### CODE REVIEW

**Comment by dpryan79** [comment]
This should at least build on Linux and OSX, no clue abut Windows.

**Comment by isuruf** [comment]
We were going to change the R layout in Windows for the new version right?

**Comment by mingwandroid** [comment]
I need to keep defaults R aligned with MRO releases, no need for conda-forge to worry about that though.

**Comment by mingwandroid** [comment]
Totally happy for cf to proceed with 3.5.1

**Comment by bgruening** [comment]
@conda-forge-admin, please rerender

**Comment by bgruening** [comment]
> We were going to change the R layout in Windows for the new version right?

Are we? You mean to enable `noarch: generic` builds? Who is working on this?

**Comment by mingwandroid** [comment]
Before that you need the interpreter to have the adjusted layout, but regardless of whether you do `noarch: generic` or not adopting the layout change now shouldn't be harmful.

Do you want to re-sync with my recipe here though? You'd get the Windows layout changes and also openblas is now used on linux and macOS (as it was on 3.4.3).

**Comment by bgruening** [comment]
> Do you want to re-sync with my recipe here though? You'd get the Windows layout changes and also openblas is now used on linux and macOS (as it was on 3.4.3).

That would be awesome!

**Comment by mingwandroid** [comment]
OK I'll see if I can update my r-base to 3.5.1 then we can consider a PR?

**Comment by bgruening** [comment]
> OK I'll see if I can update my r-base to 3.5.1 then we can consider a PR?

:+1: Thanks Ray!

**Comment by ocefpaf** [comment]
> Do you want to re-sync with my recipe here though? 

I'm :+1: on syncing but I'm also OK merging this as-is and work on the syncing in a new PR.

**Comment by bgruening** [comment]
@mingwandroid let me know if you want us to merge this one before you start working on a new one.

**Comment by mingwandroid** [comment]
Go for it, I'll not bother trying to keep my own history of changes as the rebase would be tricky so I'll just base it on top of what you have when I get finished.

**Comment by bgruening** [comment]
Great! Thanks @dpryan79 for pushing this forward and thanks @mingwandroid for you prompt response!

**Comment by dpryan79** [comment]
Thanks everyone!

**Comment by jdblischak** [comment]
Thanks @dpryan79!

A quick status update as we wait on #57: the CI builds show macOS and Linux passing but Windows failing. However, a Windows package was uploaded to Anaconda Cloud, and I was able to install and run R 3.5.1 on my local Windows machine.

**Pull request merged**
