### PR TITLE
WIP: r-base 3.4.1 update

### PR DESCRIPTION
**Pull request by bgruening**
* still no xlibs included
* zlib can crash as I tried again to stick to [pin the slow way](https://github.com/conda-forge/conda-forge.github.io/blob/0661e2ecf4b213ddf36350ca100a5a820eb17eb7/scripts/pin_the_slow_way.py#L40-L85)

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks for tackling this @bgruening! Everything LGTM. Waiting for the green.

**Comment by bgruening** [comment]
@ocefpaf do you know about this one?
```
No BINSTAR_TOKEN present, so no upload is taking place. The distribution just built is not already available for conda-forge.
```

**Comment by jakirkham** [comment]
Does `r-base` have a new token? If not, please see the ["Near term" plan]( https://github.com/conda-forge/conda-forge.github.io/issues/426#issuecomment-321897876 ) on how to fix this. Thanks.

**Comment by bgruening** [comment]
@jakirkham I did that and merged master into this branch. It dows not seem to help :(

**Comment by jakirkham** [comment]
Ok. AFAICT it seems fine now. What issue are you seeing?

**Comment by bgruening** [comment]
Travis is still failing with the same binstar error message.

**Comment by jakirkham** [comment]
Not seeing this in the [most recent build log]( https://travis-ci.org/conda-forge/r-base-feedstock/builds/263912345 ). Could you please point me to where you are seeing the token is outdated?

**Comment by bgruening** [comment]
@jakirkham I rebased everything and a new PR is here: https://github.com/conda-forge/r-base-feedstock/pull/21
With the error here: https://travis-ci.org/conda-forge/r-base-feedstock/builds/264069448#L2222

**Comment by jakirkham** [comment]
Thanks @bgruening. It is expected for the token to be undefined in the PR. This is what blocks uploads from occurring in the PR. The failure appears to be caused by [`grep texlive`]( https://travis-ci.org/conda-forge/r-base-feedstock/builds/264069448#L2222 ).

**Comment by bgruening** [comment]
I know, but the failure is not expected right? :) Is this unrelated to the token problems and we found a new bug?

**Comment by bgruening** [comment]
Oh, ok what you are saying is that this is a normal message?

**Comment by jakirkham** [comment]
All of the above. :) To summarize, there appears to be a failure that is build related (not token related).

**Pull request closed without merging**
