### PR TITLE
Re-arrange Windows R layout to be the same as Unix

### PR DESCRIPTION
**Pull request by mingwandroid**
This is so that we can share noarch packages directly.

### CODE REVIEW

**Comment by isuruf** [comment]
Will the already built R packages work with this change?

**Comment by mingwandroid** [comment]
No. They need to be rebuilt but we pin the r-base dependency exactly anyway. Need to rebuild the whole set. Probably best at 3.5 release time?

**Comment by ocefpaf** [comment]
> Need to rebuild the whole set. Probably best at 3.5 release time?

Yep. Let's do this for `R 3.5.0` then.

**Comment by jakirkham** [comment]
cc @jdblischak

**Comment by jdblischak** [comment]
A few quick notes:

1. This build failed on Windows because we haven't successfully built R 3.4.1 for Windows since build number 1. If you look at the CI builds for R packages, r-base-3.4.1-3 is installed on Travis and CircleCI, but r-base-3.4.1-1 is installed on AppVeyor. See #40 
1. If we change the installation path for Windows, we'll need to update all the GPL'd packages that include the Windows-specific path to the GPL license files
1. The original plan was to wait until R 3.5.1 (to be released in late June) to build a new r-base package for conda-forge. Due to limitations in CI (and human) resources, we aim to support one version per minor release, and the x.x.1 allows for the first round of bug fixes after a new minor release

**Comment by jdblischak** [comment]
R 3.5.1 will be released on July 2

https://stat.ethz.ch/pipermail/r-announce/2018/000629.html

**Comment by jdblischak** [comment]
The Windows build has been fixed (the URL to download MiKTeK was broken; see #40 and #44).

@mingwandroid Would you be able to rebase your commits onto master? Note that you'll get a merge conflict because I also fixed the spacing in the Jinja2 variables defined in meta.yaml. If you'd prefer, I can perform the rebase and open a new PR (either on your branch or in the main repo).

**Comment by jdblischak** [comment]
Thanks @mingwandroid! I was referring to rebasing only the small number of commits in this PR, but comparing all the changes that have been made to the defaults r-base is also useful.

I created a new Issue to coordinate all the updates that need to be made the conda-forge r-base feedstock. Please share your thoughts in #46. Thanks!

**Comment by jdblischak** [comment]
R 3.5.1 has been released ([release notes](https://stat.ethz.ch/pipermail/r-announce/2018/000630.html))

**Comment by bgruening** [comment]
@jdblischak https://github.com/conda-forge/r-base-feedstock/pull/48

**Comment by bgruening** [comment]
@mingwandroid is working on a new iteration of this PR for 3.5.1

**Pull request closed without merging**
