### PR TITLE
Use POSIX scripts for de-/activation scripts

### PR DESCRIPTION
**Pull request by mbargull**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ x Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes gh-221

### CODE REVIEW

**Review by xhochy — APPROVED** [review]

**Comment by isuruf** [comment]
Can't we use
```yaml
shellcheck:
  enabled: true
```

in conda-forge.yml?

**Comment by mbargull** [comment]
> Can't we use
> 
> ```yaml
> shellcheck:
>   enabled: true
> ```
> 
> in conda-forge.yml?

I wasn't aware of that option to be honest.
But no, it wouldn't work since that one has, e.g., `--shell=bash` hard coded:
https://github.com/conda-forge/conda-smithy/blob/v3.36.2/conda_smithy/lint_recipe.py#L798
(and that CLI arg would override any `shell=sh` directive).

**Comment by isuruf** [comment]
>  But no, it wouldn't work since that one has, e.g., --shell=bash hard coded:

Maybe that should be added as an option. Can you open an issue in conda-smithy?

As for this PR, I'd rather have this test with `shellcheck` in `build-r-base.sh` rather than the test section which requires `shellcheck` only in `build_platform` and not `target_platform`.

**Comment by wolfv** [comment]
Isn't the shellcheck pretty orthogonal to this fix? :)

**Comment by mbargull** [comment]
> Isn't the shellcheck pretty orthogonal to this fix? :)

That's a question on whether one sees regression tests as orthogonal to fixes or not ;).
So, IMO, no, since I'd want us to avoid to regress on this.

**Comment by mbargull** [comment]
> Maybe that should be added as an option. Can you open an issue in conda-smithy?

https://github.com/conda-forge/conda-smithy/issues/1965

**Pull request merged**
