### PR TITLE
Another attempt to fix R 3.3.2

### PR DESCRIPTION
**Pull request by jdblischak**
This is a follow up attempt to my other PR #31. For this attempt, I reverted back to the last working commit (build 5), updated the pins, and added back the [zlib patch](https://github.com/conda-forge/r-base-feedstock/commit/5c6666a6ed7e332d7bc2d9d92b479101dff41d88). Unfortunately the zlib patch no longer seems to work (it had worked before in #28).

Any ideas? @isuruf @ocefpaf @bgruening 

Other issues:

1. There also seems to be an issue dealing with timezones, but that is not manifesting itself here at least (i.e. it will build on Windows now). See https://github.com/conda-forge/r-downloader-feedstock/pull/1#issuecomment-356981750

1. [R 3.3.2 builds 6 and 7](https://anaconda.org/conda-forge/r-base/files?version=3.3.2) were marked as broken because they lost the `include` directory (Issue #30). Do we have any idea how this happened or how we can prevent it from happening again? How was it diagnosed in the first place? Lastly, how can I install a specific build of a conda package for testing? I wasn't able to find this in the docs. I attempted to `conda install` both `r-base==3.3.2-4` and `r-base==3.3.2_4`, but neither worked.

1. Some of the Windows software cannot be pinned because the software has not been updated. For the long-term support of Windows on conda-forge (not just this recipe), is there a plan to update these? Or will conda-build 3 resolve this?

Lastly, @isuruf, I added you as a maintainer since you frequently help me with this recipe. Please let me know if this is OK.

### CODE REVIEW

**Comment by jdblischak** [comment]
I'm happy to do the grunt work trying to update the pins for R 3.3.2, but I don't understand why everything is failing so poorly (or why my previous attempt in #28 appeared to work but then somehow caused #30). Could anyone please take a look and give me some advice of what to experiment with next?

**Comment by isuruf** [comment]
Can you send a PR reverting the branch to last working build and see if it still works?

**Comment by jdblischak** [comment]
Dropping R 3.3.2. See #36

**Comment by jdblischak** [comment]
> R 3.3.2 builds 6 and 7 were marked as broken because they lost the include directory (Issue #30). Do we have any idea how this happened or how we can prevent it from happening again? How was it diagnosed in the first place? Lastly, how can I install a specific build of a conda package for testing? I wasn't able to find this in the docs. I attempted to conda install both r-base==3.3.2-4 and r-base==3.3.2_4, but neither worked.

For my future self, this is the syntax to install a specific build number:

```
conda install r-base=3.3.2=4
```

**Pull request closed without merging**
