### PR TITLE
Bump for pinnings

### PR DESCRIPTION
**Pull request by dpryan79**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

A few packages (such as [r-magick](https://github.com/conda-forge/r-magick-feedstock/pull/5) ) appear to be failing to due updates in pinnings (namely, cairo). This is an attempt to correct that.

### CODE REVIEW

**Comment by dpryan79** [comment]
This is still pulling in an old version of `cairo` for some reason.

**Comment by dpryan79** [comment]
Hmm, it seems that on OSX the new cairo pinning is simply ignored, or rather it's installed and then downgraded once the compilers are brought in.

**Comment by dpryan79** [comment]
The issue is the `texlive-core` hasn't been updated since 2017.

**Comment by bgruening** [comment]
Would https://github.com/conda-forge/tectonic-feedstock be an alternative?

**Comment by dpryan79** [comment]
@bgruening Maybe? I can happily say that I have never written anything of substance in Latex :)

**Pull request closed without merging**
