### PR TITLE
Restore deactivate-r-base.sh

### PR DESCRIPTION
**Pull request by PertuyF**
Restores `$CONDA_PREFIX/etc/conda/deactivate.d/deactivate-r-base.sh` script which was lost since [commit `6b81c0f`](https://github.com/conda-forge/r-base-feedstock/compare/6b81c0f..HEAD#diff-44a73bcc045c193c3bd45da87994b03bL359).

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by PertuyF** [comment]
@conda-forge-admin, please rerender

**Comment by PertuyF** [comment]
@conda-forge/help-r  Anyone to help with this please?

**Comment by PertuyF** [comment]
@conda-forge/r-base

**Comment by jdblischak** [comment]
> Restores `$CONDA_PREFIX/etc/conda/deactivate.d/deactivate-r-base.sh` script which was lost since [commit `6b81c0f`](https://github.com/conda-forge/r-base-feedstock/compare/6b81c0f..HEAD#diff-44a73bcc045c193c3bd45da87994b03bL359).

@PertuyF Thanks for catching this regression and submitting a fix!

> Anyone to help with this please?

The builds are failing to download the file `ff_ci_pr_build.py` which no longer exists at https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py. You did the right thing by trying to rerender to update the CI scripts. Hopefully by now the updated scripts are available.

@conda-forge-admin, please rerender

**Comment by jdblischak** [comment]
Looks like the Windows build is failing during the [MiKTeX](https://miktex.org/) installation. I suspect that the download URL might need to be updated, since we've had to do this before in the past.

**Comment by PertuyF** [comment]
Updating MiKTeX url worked, but now Azure pipeline for win vs2008 failed on: `mv: cannot move 'D:/bld/r-base_1550523559484/work/lib/R/Tcl/Library/mingw-w64/lib' to 'D:/bld/r-base_1550523559484/work/lib/R/Tcl/lib': Permission denied`.
It is strange as installation of  `m2w64` succeeded for win vs2015 build.

**Comment by PertuyF** [comment]
Just to mention, the mirror used for MiKTeX has an url of the form `https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x86/miktex-portable-${MIKTEX_VER}.exe`, currently used in the recipe, which requires to specify the version.

But also `https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x86/miktex-portable.exe` which looks more stable and could prevent future break. Although at the price of not knowing which version was used from the build.sh script...

Do you think we should use this one? or keep the current url?

**Comment by jdblischak** [comment]
@isuruf Could you please provide your thoughts on 1) the failed vs2008 Azure build, and 2) the MiKTeK download URL?

From @PertuyF:

> Azure pipeline for win vs2008 failed on: `mv: cannot move 'D:/bld/r-base_1550523559484/work/lib/R/Tcl/Library/mingw-w64/lib' to 'D:/bld/r-base_1550523559484/work/lib/R/Tcl/lib': Permission denied`.

> But also `https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x86/miktex-portable.exe` which looks more stable and could prevent future break. Although at the price of not knowing which version was used from the build.sh script...

**Comment by jdblischak** [comment]
The Azure pipeline failure can probably be ignored. See https://github.com/conda-forge/staged-recipes/pull/7822#issuecomment-465898219

**Comment by PertuyF** [comment]
@jdblischak, @isuruf  what should we do with this PR? merge as-is? rerender?

Should we finally change miktex url to the portable version?

**Comment by jdblischak** [comment]
> Should we finally change miktex url to the portable version?

@PertuyF I think it is more important to know which version was used with each build.

> what should we do with this PR? merge as-is? rerender?

@bgruening @croth1 How do we want to coordinate this PR with #78?

**Comment by croth1** [comment]
@jdblischak I just wanted to encourage a rerender due to very old pins. If this one is ok, please go ahead, merge it and close mine.

**Comment by bgruening** [comment]
@conda-forge-admin, please re-render

@croth1 sounds like a plan!

**Comment by PertuyF** [comment]
@bgruening Looks like we're good to go 😄 
Thanks all!

**Comment by bgruening** [comment]
Ok, let go for it and reserve some time for potential fallouts :)

**Pull request merged**
