### PR TITLE
Update run dependencies for capabilities() and grSoftVersion()

### PR DESCRIPTION
**Pull request by dbast**
…tests

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Can you revert the last commit so that we can keep this recipe in sync with defaults?

**Comment by dbast** [comment]
@isuruf I intended to do 3 commits here
1. Adding the two functions call capabilities() and grSoftVersion() to tests (done) -> green
2. Moving libxt from yum_requirements as xorg-libxt to host dependencies (done) -> intended to be red when the two functions as called in tests, but seems to be green
3. Adding xorg-libxt to run dependencies (not yet pushed) -> intended to be green again.

Background to this is:
* https://github.com/conda-forge/r-rmarkdown-feedstock/pull/24 
* https://github.com/conda-forge/r-rmarkdown-feedstock/pull/23
where it was discovered that xorg-libxt is required and a currently missing dependency to not get a segmentation fault wenn calling capabilities() and grSoftVersion()

@isuruf How do you propose to proceed here? keep libxt-devel in yum_requirementes but still also add xorg-libxt to run dependencies?

**Comment by dbast** [comment]
@isuruf Now all three commits are there. Can rebase and remove the second one.

**Comment by dbast** [comment]
Removed second commit "cd3aed4 Move libxt from yum_requirements to host dependencies"

**Comment by jdblischak** [comment]
> Can you revert the last commit so that we can keep this recipe in sync with defaults?

Alternatively we could update the defaults recipe as well. If we think it is better to rely on the `xorg-` conda binaries over the RPM binaries, then wouldn't it make sense to make this improvement to both the conda-forge and defaults recipes?

**Comment by bgruening** [comment]
@conda-forge-bot please rerender

**Comment by bgruening** [comment]
@conda-forge-admin, please re-render

**Comment by isuruf** [comment]
@mingwandroid, thoughts?

**Comment by mingwandroid** [comment]
> then wouldn't it make sense to make this improvement to both the conda-forge and defaults recipes?

Anaconda have no plans to use the xorg packages at present. The recipe would have to check channel_targets  and switch dependencies based on that for us to be able to share it. Easy enough to do though and we can do that over at anaconda when we resync.

**Comment by bgruening** [comment]
@conda-forge-admin, please re-render

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@conda-forge-admin, please rerender

**Comment by bgruening** [comment]
@dbast I'm not sure why the bot can not update your PR, could you update it please or should I rerender and push to your PR?

**Pull request merged**
