### PR TITLE
R 3.6.1

### PR DESCRIPTION
**Pull request by dpryan79**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dpryan79** [comment]
Linux builds, so that's something.

**Comment by dpryan79** [comment]
BTW, this is very much WIP, I blindly copied over patches from the defaults channel and the changes in these need to be reviewed before merging.

**Comment by dpryan79** [comment]
Wow, windows even builds. Just need to figure out OSX. I'll be offline for a few days, so if any one wants to take a stab at that it'd be most appreciated :)

**Comment by dpryan79** [comment]
Success! Someone want to hit rerun on windows? There was a networking issue.

**Comment by dpryan79** [comment]
BTW, should conda-forge/r be added as a maintainer?

**Comment by dpryan79** [comment]
@conda-forge-admin, please rerender

**Comment by dpryan79** [comment]
Grr, CRAN networking problems again. Anyway, this will build once that's resolved.

**Comment by isuruf** [comment]
Also, remember to pull in changes from https://github.com/conda-forge/r-base-feedstock/pull/80. (It's still WIP, but I'll have it ready today. That PR has to be merged in a new version to avoid breaking packages.)

**Comment by bgruening** [comment]
@isuruf can you point your #80 against this branch?

Thanks for working on it!

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by dpryan79** [comment]
Is this waiting on anything else?

**Comment by ocefpaf** [comment]
LGTM. @isuruf are you planning on any extra commits or is this ready to be merged?

**Comment by isuruf** [comment]
Ready to merge

**Comment by ocefpaf** [comment]
Thanks for the awesome work on this PR @dpryan79 and @isuruf!

**Pull request merged**
