### PR TITLE
Merge 3.3.2 into master

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by jakirkham** [comment]
CI can be ignored as this is only preserving history not actually making any changes.

**Comment by jakirkham** [comment]
The AppVeyor failure should be fixed by re-rendering. Added PR ( https://github.com/conda-forge/r-base-feedstock/pull/39 ) independently of this to re-render the feedstock

**Comment by jakirkham** [comment]
Have updated to include the merge of PR ( https://github.com/conda-forge/r-base-feedstock/pull/39 ). Otherwise this is still a no-op PR excepting for the history being pulled in.

CI can still be ignored. Tried to skip CI, but CircleCI and AppVeyor didn't comply.

Please merge at your discretion.

**Comment by jdblischak** [comment]
> CI can still be ignored. Tried to skip CI, but CircleCI and AppVeyor didn't comply.

@jakirkham AppVeyor only skips if `[ci skip]` is in the title, not the body. I haven't been able to get CircleCI to skip builds either.

**Comment by jakirkham** [comment]
Yeah, I've been talking to AppVeyor about this. It was not always that way. This was a change they made late last year. They are interested in fixing this somehow. Guessing they are just swamped with other things. ( https://github.com/appveyor/ci/issues/1865 )

CircleCI sort of worked in 1.0, but stopped working in 2.0. Also there is something subtle about how they did this where it doesn't work on PRs, but may work on branches. Haven't had time to verify, but that was the impression I got last time I played with it.

**Comment by jdblischak** [comment]
Since @jakirkham has gone through the trouble of persevering the history of the now deleted 3.3.2 branch, I'd like to have it merged into master unless there are specific objections to the strategy of merging the branch and then overwriting the merge commit.

ping @bgruening @ericdill

**Comment by ericdill** [comment]
No objections here

**Pull request merged**
