### PR TITLE
Fix build to remove rtools parts

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mbargull** [comment]
Thanks for having dug into this.
diff excerpt:
```diff
diff -ru0 r-base-4.4.1-hc390f20_9/lib/R/etc/Rcmd_environ r-base-4.4.1-hc390f20_10/lib/R/etc/Rcmd_environ
-R_RTOOLS44_PATH="${RTOOLS44_HOME:-c:/rtools44}/x86_64-w64-mingw32.static.posix/bin;${RTOOLS44_HOME:-c:/rtools44}/usr/bin"
+# INSTALLER-BUILD-x86_64:R_RTOOLS44_PATH="${RTOOLS44_HOME:-c:/rtools44}/x86_64-w64-mingw32.static.posix/bin;${RTOOLS44_HOME:-c:/rtools44}/usr/bin"
-PATH="${R_CUSTOM_TOOLS_PATH:-${R_RTOOLS44_PATH}};${PATH}/"
+# INSTALLER-BUILD:PATH="${R_CUSTOM_TOOLS_PATH:-${R_RTOOLS44_PATH}};${PATH}/"
diff -ru0 r-base-4.4.1-hc390f20_9/lib/R/etc/x64/Makeconf r-base-4.4.1-hc390f20_10/lib/R/etc/x64/Makeconf
-LOCAL_SOFT ?= D:/bld/r-base-split_1719815341864/_h_env/Library
+LOCAL_SOFT ?= D:/bld/r-base-split_1719893459885/_h_env/Library
- R_INSTALLER_BUILD = no
+# INSTALLER-BUILD: R_INSTALLER_BUILD = yes
-     RTOOLS44_HOME ?= c:/rtools44
-     LOCAL_SOFT = $(subst \,/,$(RTOOLS44_HOME))/x86_64-w64-mingw32.static.posix
+    # INSTALLER-BUILD-x86_64: RTOOLS44_HOME ?= c:/rtools44
+    # INSTALLER-BUILD-x86_64: LOCAL_SOFT = $(subst \,/,$(RTOOLS44_HOME))/x86_64-w64-mingw32.static.posix
diff -ru0 r-base-4.4.1-hc390f20_9/lib/R/library/base/R/Rprofile r-base-4.4.1-hc390f20_10/lib/R/library/base/R/Rprofile
-     setRtools44Path <- 1
+    # INSTALLER-BUILD: setRtools44Path <- 1
```
looking over the source, I can't really make out if this patch suffices, but I restarted the `r-matrix` build just to see.

**Comment by mbargull** [comment]
Okay, I misread parts of the code; removing the `PATH=` etc. makes sense.
Backporting to 4.3 also makes sense -- but do you know why the builds for `r-matrix` did not fail for 4.3 even without that change?

**Comment by isuruf** [comment]
Probably because `c:/rtools44` was in Azure and `c:/rtools43` was not

**Comment by mbargull** [comment]
Ah! Man, it's so much simpler when we can more tightly control the build env (chroot/container-based).
ty

**Pull request merged**
