### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Going to merge this and if something breaks we can remove the builds.

**Comment by mbargull** [comment]
Thanks for looking into that!

It'd be helpful if you add a short description with references for pull requests.
Doesn't have to be much (I actually prefer it to be succinct -- to not waste your and others' time), e.g.,
> Fixes `<problem>` encountered at `<issue link>` .
> refs:
>     - `<additional link 1>`
>     - `<additional link 2>`

Adding references tremendously helps with (re-)discoverability and traceability (esp. once time passes).

**Comment by mfansler** [comment]
To what extent should the changes here be applied to the other branches?

Currently, appears that removing these pinned dependencies from the `main` branch has led to a situation where the other branches no longer get migrations for their distinct dependencies. A specific example is the [`libxml2212`](https://conda-forge.org/status/#libxml2212) migration. A [`proj931` migration PR](https://github.com/conda-forge/r-rgdal-feedstock/pull/82) on `r-rgdal-feedstock` cannot solve a valid host environment for any R 4.2 builds due to the latest `libgdal` using `libxml2=2.12`, but no `r-base=4.2` builds have built against that. That is, `main` here no longer has `libxml2`, while the other branches still include it, but there have been no PRs from `libxml2212` migration for them.

**Comment by jdblischak** [comment]
The lack of libxml2 migration to the 4.2.x branch is also causing a problem in https://github.com/conda-forge/r-tiledb-feedstock/pull/70#issuecomment-1868049782. Can we manually open a PR to migrate to libxml2 2.12?

**Comment by jdblischak** [comment]
For the short-term, I manually opened a PR to migrate r-base 4.2 to libxml2 2.12 (https://github.com/conda-forge/r-base-feedstock/pull/288). But longer-term it would be nice to somehow address the lack of automated migrations to these supported branches

**Comment by mbargull** [comment]
> longer-term it would be nice to somehow address the lack of automated migrations to these supported branches

Yep, I've opened https://github.com/regro/cf-scripts/issues/1979 to track this.
But I'm not one of our infrastructure gurus, so can't really tell how much has to be done to get this working...

**Pull request merged**
