### PR TITLE
Update URL to download MiKTeX executable for Windows build.

### PR DESCRIPTION
**Pull request by jdblischak**
cc: @isuruf
xref: #40

### CODE REVIEW

**Comment by jdblischak** [comment]
It passed! For the sake of consistency, I'd like to merge this PR as is. This will upload a "conda-build 2" version of r-base 3.4.1 with updated pins for Windows (i.e. win-64/r-base-3.4.1-3.tar.bz2). Then we can migrate to conda-build 3 in a subsequent update. Any objections to this plan?

**Comment by isuruf** [comment]
I don't think it will upload since the files are already there even if they are under a different label

**Comment by jdblischak** [comment]
> I don't think it will upload since the files are already there even if they are under a different label

Good point. I didn't think of that. I could bump the build number, though that would upload redundant versions for linux-64 and osx-64.

**Comment by isuruf** [comment]
> that would upload redundant versions for linux-64 and osx-64.

That's fine

**Comment by jdblischak** [comment]
@bgruening @ocefpaf @jakirkham Could you please review this PR?

**Comment by ocefpaf** [comment]
LGTM! Thanks @isuruf and @jdblischak for figuring this out and fixing it!

If the CIs passes let's fix those lints and get this merged!

**Comment by jdblischak** [comment]
CI and lints have passed!

**Comment by jdblischak** [comment]
The AppVeyor and Travis builds are listed as failing due to an error at the upload step. However, the binaries still appear to be uploaded, so I'm not sure what happended:

https://anaconda.org/conda-forge/r-base/files

**Comment by ocefpaf** [comment]
Hopefully they are OK. I only have a Linux machine to test :-(

**Comment by jdblischak** [comment]
I confirmed that build 4 works on both macOS and Windows. Thus it's just an inconvenience that the builds are listed are failing.

**Comment by ocefpaf** [comment]
I restarted the CIs and they are OK now...

**Pull request merged**
