### PR TITLE
Manual run of pcre2 10.36 migration

### PR DESCRIPTION
**Pull request by xhochy**
Bot is thinking that this is not solvable but it should be. The errors are about `osx-arm64` build dependencies.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
Difference in the build environment for `osx-arm64` to master:

```diff
--- build_success.txt	2021-03-02 09:55:10.000000000 +0100
+++ build_fail.txt	2021-03-02 09:56:13.000000000 +0100
@@ -6,17 +6,17 @@
 cctools_osx-arm64:           949.0.1-h9541561_19       conda-forge
 clang:                       11.0.1-h694c41f_1         conda-forge
 clang-11:                    11.0.1-default_hf8bb9ca_1 conda-forge
-clang_osx-arm64:             11.0.1-h40be2b1_0         conda-forge
+clang_osx-arm64:             11.0.1-h40be2b1_2         conda-forge
 clangxx:                     11.0.1-default_hf8bb9ca_1 conda-forge
-clangxx_osx-arm64:           11.0.1-hc50fe25_0         conda-forge
+clangxx_osx-arm64:           11.0.1-hc50fe25_2         conda-forge
 compiler-rt:                 11.0.1-h654b07c_0         conda-forge
 compiler-rt_osx-64:          11.0.1-h8c5fa43_0         conda-forge
 fontconfig:                  2.13.1-hd23ceaa_1004      conda-forge
 freetype:                    2.10.4-h4cff582_1         conda-forge
 gettext:                     0.19.8.1-h7937167_1005    conda-forge
-gfortran_impl_osx-64:        9.3.0-h8668ab3_17         conda-forge
-gfortran_impl_osx-arm64:     11.0.0.dev0-h812bd78_17   conda-forge
-gfortran_osx-arm64:          11.0.0.dev0-h6d48cdc_12   conda-forge
+gfortran_impl_osx-64:        9.3.0-h9cc0e5e_19         conda-forge
+gfortran_impl_osx-arm64:     11.0.0.dev0-ha2db388_19   conda-forge
+gfortran_osx-arm64:          11.0.0.dev0-h64a2375_13   conda-forge
 gmp:                         6.2.1-h2e338ed_0          conda-forge
 gnuconfig:                   2020.11.07-hd8ed1ab_0     conda-forge
 graphite2:                   1.3.13-h2e338ed_1001      conda-forge
@@ -33,13 +33,13 @@
 libedit:                     3.1.20191231-h0678c8f_2   conda-forge
 libev:                       4.33-haf1e3a3_1           conda-forge
 libffi:                      3.3-h046ec9c_2            conda-forge
-libgfortran-devel_osx-64:    9.3.0-h6c81a4c_17         conda-forge
-libgfortran-devel_osx-arm64: 11.0.0.dev0-hdc626ea_17   conda-forge
-libgfortran5:                9.3.0-h6c81a4c_17         conda-forge
-libglib:                     2.66.4-h7424822_2         conda-forge
+libgfortran-devel_osx-64:    9.3.0-h6c81a4c_19         conda-forge
+libgfortran-devel_osx-arm64: 11.0.0.dev0-hdc626ea_19   conda-forge
+libgfortran5:                9.3.0-h6c81a4c_19         conda-forge
+libglib:                     2.66.7-hd556434_1         conda-forge
 libiconv:                    1.16-haf1e3a3_0           conda-forge
 libllvm11:                   11.0.1-h223d4b2_0         conda-forge
-libnghttp2:                  1.41.0-h7580e61_2         conda-forge
+libnghttp2:                  1.43.0-h07e645a_0         conda-forge
 libpng:                      1.6.37-h7cec526_2         conda-forge
 libssh2:                     1.9.0-h8a08a2b_5          conda-forge
 libxml2:                     2.9.10-h802ca4f_3         conda-forge
@@ -51,7 +51,7 @@
 mpfr:                        4.0.2-h72d8aaf_1          conda-forge
 ncurses:                     6.2-h2e338ed_4            conda-forge
 openjdk:                     11.0.8-hb0a8c7a_0         conda-forge
-openssl:                     1.1.1i-h35c211d_0         conda-forge
+openssl:                     1.1.1j-hbcf498f_0         conda-forge
 pcre:                        8.44-hb1e8313_0           conda-forge
 perl:                        5.32.0-hbcb3906_0         conda-forge
 pixman:                      0.40.0-hbcb3906_0         conda-forge
 ```

Fortran related stuff was updated from build `17`  to `19`, this is the most visible difference.

**Comment by xhochy** [comment]
`osx-arm64` builds locally using

```
% git diff                                                                                                                   :(
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index a24b497..9056b8d 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -56,6 +56,10 @@ outputs:
         - {{ compiler('c') }}                # [not win]
         - {{ compiler('cxx') }}              # [not win]
         - {{ compiler('fortran') }}          # [not win]
+        - gfortran_impl_osx-64 9.3.0 *_17
+        - gfortran_impl_osx-arm64 11.0.0.dev0 *_17
+        - libgfortran-devel_osx-64 9.3.0 *_17
+        - libgfortran-devel_osx-arm64 11.0.0.dev0 *_17
         - {{ compiler('m2w64_c') }}          # [win]
         - {{ compiler('m2w64_cxx') }}        # [win]
         - {{ compiler('m2w64_fortran') }}     # [win]
```

@isuruf Do you have an idea how to fix in a more beautiful way?

**Comment by xhochy** [comment]
Builds with `_18` also fail.

**Comment by isuruf** [comment]
Not really. Can you open a bug report at https://github.com/iains/gcc-darwin-arm64 with the preprocessed source?

**Comment by xhochy** [comment]
> Not really. Can you open a bug report at https://github.com/iains/gcc-darwin-arm64 with the preprocessed source?

Actually, no. I have no understanding of the Fortran toolchain and I don't know how to produce the preprocessed source nor do I know how to boil this down to a more minimal example than the thousands-lines-of-code source that produces the segmentation fault.

**Comment by xhochy** [comment]
Merging to get the rebuild going on.

**Pull request merged**
