### PR TITLE
Enable aarch64 and ppc64le builds

### PR DESCRIPTION
**Pull request by jayfurmanek**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #107 

Dependencies are there now for aarch64 as well, so this new PR will enable builds for both aarch64 and ppc64le. The TexLive/ICU issues have also been worked out, so no other changes needed.

I'm opening this manually because the migrator is hung up on dependencies that are either not needed for aarch64/ppc64le or are already available.

### CODE REVIEW

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
@hmaarrfk FYI

**Comment by jayfurmanek** [comment]
ah, looks like `bwidget` is still needed on aarch64.

**Comment by jayfurmanek** [comment]
https://github.com/conda-forge/bwidget-feedstock/pull/1

**Comment by mariusvniekerk** [comment]
Error on drone (aarch64)
```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-aarch64: {'libsm-devel-cos7-aarch64', 'libxt-devel-cos7-aarch64', 'java-1.7.0-openjdk-cos7-aarch64', 'libice-devel-cos7-aarch64', 'libxt-cos7-aarch64'}
```

**Comment by isuruf** [comment]
ping @conda-forge/arm-arch

**Comment by hmaarrfk** [comment]
cdts are notorious hard to get through the review process

A bit of help here would be appreciated
https://github.com/conda-forge/staged-recipes/pull/10516

**Pull request closed without merging**
