### PR TITLE
use external BLAS/LAPACK on osx-arm64

### LINKED ISSUE #249: BLAS variants ignored on osx-arm64
## Summary
Installing different Conda Forge `blas` variants has no effect on base R matrix operations performance. R uses the `lib/R/lib/Rblas.dylib` for BLAS operations, which appears to perform identically with our Netlib build of `libblas.dylib`.

Symlinking the `lib/R/lib/libRblas.dylib` to `../../libblas.dylib` enables R to use the BLAS variants.

## Initial Benchmarking
I ran some basic benchmarking tests to see how BLAS variants impact R performance on **osx-arm64** platform. I already know that [they impact Python `numpy`](https://stackoverflow.com/a/70241376/570918), with Accelerate making a huge difference. I was really surprised to find that **they all performed identically.**

**bench-prcomp.R**
```r
library(microbenchmark)

set.seed(20230506)
NROW=1000L
NCOL=1000L

mat <- matrix(rnorm(NROW*NCOL, 10), NROW, NCOL)

microbenchmark(prcomp(mat), times=10)
```

**Environments**
```bash
mamba create -n r42_accelerate r-base=4.2 r-microbenchmark 'blas=*=accelerate'
mamba create -n r42_netlib r-base=4.2 r-microbenchmark 'blas=*=netlib'
mamba create -n r42_openblas r-base=4.2 r-microbenchmark 'blas=*=openblas'
```

**Results**
```r
$ mamba run -n r42_accelerate Rscript bench-prcomp.R
Unit: seconds
        expr    min       lq     mean   median      uq      max neval
 prcomp(mat) 1.8176 1.824767 1.846034 1.828512 1.86154 1.927992    10

$ mamba run -n r42_netlib Rscript bench-prcomp.R
Unit: seconds
        expr      min       lq     mean  median       uq      max neval
 prcomp(mat) 1.819297 1.826732 1.843118 1.83046 1.868234 1.871313    10

$ mamba run -n r42_openblas Rscript bench-prcomp.R
Unit: seconds
        expr      min       lq     mean   median       uq      max neval
 prcomp(mat) 1.822875 1.823559 1.846244 1.831912 1.871775 1.886548    10
```

They are effectively identical, which is unexpected given that Accelerate is faster when used in NumPy.

## Modified Benchmarking
Next I modified each environment by replacing the `lib/R/lib/libRblas.dylib` with a symlink to `../../libblas.dylib`. This appears to give more expected results.

**Results**
```r
$ mamba run -n r42_accelerate Rscript bench-prcomp.R
Unit: milliseconds
        expr      min      lq     mean   median       uq      max neval
 prcomp(mat) 236.2402 238.195 258.9798 249.5734 281.4831 294.9549    10

$ mamba run -n r42_netlib Rscript bench-prcomp.R
Unit: seconds
        expr     min       lq     mean   median      uq      max neval
 prcomp(mat) 1.81474 1.827195 1.842966 1.829962 1.86686 1.873634    10

$ mamba run -n r42_openblas Rscript bench-prcomp.R
Unit: milliseconds
        expr      min       lq     mean   median       uq      max neval
 prcomp(mat) 872.5037 912.5565 925.3458 929.6652 938.9488 989.4986    10
```

That is, OpenBLAS is 2X faster and Accelerate is 7X faster than the Netlib implementation, which appears to be what Conda Forge's R is delivering (at least for **osx-arm64**).

## Remarks
It is unclear whether this is intended, but I would expect not (hence the ![label: bug][~bug] label). It was discussed previously in #79, and changed in R 3.6.1 (https://github.com/conda-forge/r-base-feedstock/commit/a4b9e3f9349459a195bdfbfbdfa3ec5ccef4d150). To me it appears that using the `--with-blas=-lblas` flag in the build leads to R generating a `libRblas.dylib` using the available BLAS (which is `netlib` at build time) and this is not subsequently dynamic.

I'm unsure if this impacts other platforms. I'm also unsure if replacing with a symlink is stable. Perhaps someone knows why R still generates a `libRblas.dylib` despite the `-lblas` flag.

[~bug]: https://img.shields.io/badge/-bug-f00.svg

### PR DESCRIPTION
**Pull request by mfansler**
Resolves #249.

## Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by mfansler** [comment]
This did not resolve the issue. Still getting a rejected external BLAS/LAPACK:

```cpp
checking for dgemm_ in -lblas... yes
checking whether double complex BLAS can be used... no
configure: cannot use --with-lapack without --with-blas
configure: using internal LAPACK sources
```

with final configuration of:

```cpp
R is now configured for aarch64-apple-darwin20.0.0

  Source directory:            .
  Installation directory:      /Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh

  C compiler:                  arm64-apple-darwin20.0.0-clang  -isysroot /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/work=/usr/local/src/conda/r-base-4.3.0 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh=/usr/local/src/conda-prefix
  Fortran fixed-form compiler: arm64-apple-darwin20.0.0-gfortran  -march=armv8.3-a -ftree-vectorize -fPIC -fno-stack-protector -O2 -pipe -isystem /Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/work=/usr/local/src/conda/r-base-4.3.0 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh=/usr/local/src/conda-prefix

  Default C++ compiler:        arm64-apple-darwin20.0.0-clang++ -std=gnu++17  -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/work=/usr/local/src/conda/r-base-4.3.0 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh=/usr/local/src/conda-prefix
  C++11 compiler:              arm64-apple-darwin20.0.0-clang++ -std=gnu++11  -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/work=/usr/local/src/conda/r-base-4.3.0 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh=/usr/local/src/conda-prefix
  C++14 compiler:              arm64-apple-darwin20.0.0-clang++ -std=gnu++14  -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/work=/usr/local/src/conda/r-base-4.3.0 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh=/usr/local/src/conda-prefix
  C++17 compiler:              arm64-apple-darwin20.0.0-clang++ -std=gnu++17  -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/work=/usr/local/src/conda/r-base-4.3.0 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh=/usr/local/src/conda-prefix
  C++20 compiler:              arm64-apple-darwin20.0.0-clang++ -std=gnu++20  -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/work=/usr/local/src/conda/r-base-4.3.0 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh=/usr/local/src/conda-prefix
  C++23 compiler:              arm64-apple-darwin20.0.0-clang++ -std=gnu++2b  -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/work=/usr/local/src/conda/r-base-4.3.0 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh=/usr/local/src/conda-prefix
  Fortran free-form compiler:  arm64-apple-darwin20.0.0-gfortran  -march=armv8.3-a -ftree-vectorize -fPIC -fno-stack-protector -O2 -pipe -isystem /Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/work=/usr/local/src/conda/r-base-4.3.0 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1688746697360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh=/usr/local/src/conda-prefix
  Obj-C compiler:	       arm64-apple-darwin20.0.0-clang -g -O2 -fobjc-exceptions

  Interfaces supported:        aqua, tcltk
  External libraries:          pcre2, readline, curl
  Additional capabilities:     PNG, JPEG, TIFF, NLS, cairo, ICU
  Options enabled:             shared R library, shared BLAS, R profiling, memory profiling

  Capabilities skipped:        
  Options not enabled:         

  Recommended packages:        no
```

Any ideas welcome...

**Comment by isuruf** [comment]
Can you add a test that `$PREFIX/lib/R/lib/libRblas.dylib` does not exist in `build-r-base.sh`?

**Comment by mfansler** [comment]
@isuruf thanks for hopping in! Let me know if that test works for you - right now it's only in Darwin branch of build.

**Comment by mfansler** [comment]
Tested the artifact and confirmed that it indeed performs differently on the benchmark in #249 when changing the `blas` variants. Results are again 2X faster with OpenBLAS and 7X with Accelerate, over the Netlib baseline. 🚀

**Comment by isuruf** [comment]
Can you do the same for Linux? `.so` instead of `.dylib`

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
