### PR TITLE
trigger rebuild

### PR DESCRIPTION
**Pull request by bgruening**
This is needed because of https://github.com/conda-forge/toolchain-feedstock/pull/39

Thanks @isuruf for the hint.

### CODE REVIEW

**Comment by isuruf** [comment]
Note that windows build are broken, and has to be marked broken if this PR is merged

**Comment by bgruening** [comment]
Its filing on OSX because of to many compiler errors.

**Comment by bgruening** [comment]
Interesting still the same errors. Thanks @isuruf for trying.

**Comment by nsoranzo** [comment]
Actually I think his last commit was meant to fix the Windows build only.

**Comment by isuruf** [comment]
Windows builds are fixed. Waiting for a cairo rebuild with the fixed fontconfig for osx.

**Comment by bgruening** [comment]
> Windows builds are fixed. Waiting for a cairo rebuild with the fixed fontconfig for osx.

@isuruf anything I can help?

**Comment by isuruf** [comment]
I'm having trouble fixing https://github.com/conda-forge/cairo-feedstock/pull/37. If you can take a look at it, that'd be great.

**Comment by bgruening** [comment]
Ok, lets try again :)

**Comment by bgruening** [comment]
Great it works now. @isuruf is this ready?

**Comment by bgruening** [comment]
Thanks @ocefpaf!

**Comment by bgruening** [comment]
The package exists now, but the resolver tries to avoid it.
`conda create --dry-run r-ggplot2=3.0.0 -n foo234` will yield `r-base: 3.4.1-4` and not build 6.

`conda create --dry-run r-ggplot2=3.0.0 r-base=3.4.1=hff14c37_6 -n foo234` works for me. This is with conda 4.3.33.

**Comment by bgruening** [comment]
Latest conda version does not improve the situation :(

**Comment by bgruening** [comment]
grafik

The spotted difference is that for the latest R version `readline` comes from defaults. So we need to rebuild `readline` to depend on ncurses 6.1 (https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L360)?

**Comment by bgruening** [comment]
Anyone wants to review https://github.com/conda-forge/readline-feedstock/pull/11 ?

**Comment by bgruening** [comment]
Removing older version does not help for me. Conda would prefer R 3.2.x over 3.4.1.

**Comment by bgruening** [comment]
Also interesting: https://circleci.com/gh/conda-forge/r-plsdof-feedstock/2?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Gets the correct R version, but still readline from default and fails with the same libgfortran error that we got before this PR.

**Comment by ocefpaf** [comment]
This situation sucks :-(

I'm getting a similar situation in https://github.com/conda-forge/r-rgdal-feedstock/pull/10

**Pull request merged**
