### PR TITLE
Rebuild with glib 2.64.6

### PR DESCRIPTION
**Pull request by xhochy**
This should remove the Python runtime dependency on Linux.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Why didn't the bot issue this PR?

**Comment by xhochy** [comment]
The bot is still waiting for pango (did that manually) and Qt (no idea why this is listed as a dependency in the graph). So the bot will issue this sometime in future, I'm just impatient and wanted to see whether it works given that a Qt rebuild may take quite some time/effort.

**Comment by xhochy** [comment]
cairo isn't built anymore on OSX :)

**Comment by beckermr** [comment]
@xhochy I think the osx thing is due to a pkg-config quirk with the new split glib recipe. We need glib in host. I fixed it in the gcc 9.3.0 PR we are merging now. This one should build once it is rebased on the new master

**Comment by xhochy** [comment]
Yes, this makes sense. `glib` was available in `host` as an indirect dependency before but I fixed all dependencies to only depend on `libglib` thus it vanished from there in the last days.

**Comment by xhochy** [comment]
I'll rebase once the bot has merged the GCC PR.

**Comment by xhochy** [comment]
No more Python dependency (verified by ci) 🎉

**Pull request merged**
