### PR TITLE
Build 4.2.0 for windows

### PR DESCRIPTION
**Pull request by notestaff**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

The full update to 4.2.0 is being developed in PR #205 .  This PR takes from that PR just the non-Windows parts, using selectors.

### CODE REVIEW

**Comment by AstrobioMike** [comment]
I was wondering about this too (up'ing just linux and mac to 4.2, and keeping windows where it is due to the troubles outline in https://github.com/conda-forge/r-base-feedstock/pull/205). Was happy to see this pull request :)  

I'm unfortunately completely naive to this infrastructure, and am clueless when it comes to interpreting why the windows check is still failing here, or trying to jump-in and help move this along :/ 

To those with the knowledge/experience here, is the snag here also not something trivial to address just to get 4.2 available to linux and mac users?

**Comment by dpryan79** [comment]
@conda-forge-admin please rerender

**Comment by dpryan79** [comment]
We can use this PR to debug the windows build. It's now trying to pull in ../../../Library/mingw-w64/lib/sicudt.a rather than ../../../Library/mingw-w64/lib/libsicudt.a

**Comment by dpryan79** [comment]
One step forward at least. Now we have:

`graphappmain.o:graphappmain.c:(.text+0xf): undefined reference to `__imp___imp___argv'
graphappmain.o:graphappmain.c:(.text+0x19): undefined reference to `__imp___imp___argc'
`

A bit of googling suggests that this is a mingw version mismatch somewhere.

**Comment by isuruf** [comment]
Windows for R 4.2 is not going to work until https://github.com/conda-forge/conda-forge.github.io/issues/1654 is resolved.

**Comment by isuruf** [comment]
Keeping this open in case someone wants to work on ucrt based mingw builds.

**Comment by jsta** [comment]
Is there a reason not to use rtools as jeroen suggested in the linked thread?

**Comment by isuruf** [comment]
For two reasons,
1. We want the builds to be compatible with the rest of the ecosystem.
2. rtools uses static builds which we do not want to do.

**Pull request closed without merging**
