### PR TITLE
Rerender

### PR DESCRIPTION
**Pull request by croth1**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by croth1** [comment]
@conda-forge/r-base I cannot make much sense of the windows failures, can somebody help here?

**Comment by jdblischak** [comment]
@croth1 The Windows build failed due to an outdated MiKTeK download URL. See discussion starting at https://github.com/conda-forge/r-base-feedstock/pull/69#issuecomment-464851681

**Comment by jdblischak** [comment]
Also, the closed PR #73 is probably relevant for this PR

**Comment by croth1** [comment]
Ready for review 👍

**Pull request closed without merging**
