### PR TITLE
MNT: Re-rendered with conda-smithy 2.4.5

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by jdblischak** [comment]
Well this is a new error for me. The windows builds failed because they couldn't access the binstar token:

> WindowsError: [Error 5] Access is denied: 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\tmpg4ene_\\binstar.token'
8604


https://ci.appveyor.com/project/conda-forge/r-base-feedstock/build/1.0.90/job/deu2elanpe60keou#L8603

ping @bgruening @jakirkham

**Comment by jakirkham** [comment]
Windows complains if one tries to delete a file when it is use, which looks like the error to me after reading the traceback. Not sure why the file would still be in use. So guessing it is a spurious error. Maybe try restarting?

**Comment by jakirkham** [comment]
Should say went ahead and restarted it to see if it persists.

**Comment by jakirkham** [comment]
Failure is gone after restarting and haven't seen this elsewhere. So guessing it was in fact spurious.

**Pull request merged**
